our_chat/chat/urls.py
from django.urls import path
from .views import MyChatsView

app_name = "chat"

urlpatterns = [
    path('my-chats/', MyChatsView.as_view(), name='my_chats'),
    path('chat-with/<str:id>', MyChatsView.as_view(), name='chat-with'),
]

our_chat/our_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('chat/', include('chat.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

our_chat/user/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView, UserLogoutView, ProfileView, ProfileUpdateView, AddFriendView

app_name = "user"

urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='user-registration'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', UserLogoutView.as_view(), name='user-logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('update-profile/',ProfileUpdateView.as_view() , name='update-profile'),
    path('add-friend/',AddFriendView.as_view() , name='add-friend'),
    
]

our_chat/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User 
from PIL import Image

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    # Add or change related_name for groups and user_permissions
    groups = models.ManyToManyField(
        "auth.Group",
        related_name="customuser_set",  # Choose a suitable related_name
        related_query_name="user",
        blank=True,
        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="customuser_set",  # Choose a suitable related_name
        related_query_name="user",
        blank=True,
        help_text="Specific permissions for this user.",
    )

    def __str__(self):
        return self.username

# represents the Profile object
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    name = models.CharField(max_length=200)
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to="images/profile/",
                               default="images/profile/default.png",
                               blank=True)
    friends = models.ManyToManyField('Friend', related_name="my_friends")

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.avatar.path)
        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)
    def __str__(self):
        return self.name

# represents the Friend object
class Friend(models.Model):
    profile_one = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friendships_one", default=None)
    profile_two = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="friendships_two", default=None)

our_chat/user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput
from django.forms import ModelForm, ImageField, CharField, FileInput, Textarea
from .models import Profile

'''class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=25, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')'''


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

class UpdateProfileForm(ModelForm):
    avatar = ImageField(widget=FileInput(attrs={'class': 'form-control-file'}))
    bio = CharField(widget=Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

our_chat/user/views.py
#from django.shortcuts import render

# Create your views here.
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status

from .models import Profile, Friend
from .serializers import UserRegistrationSerializer, UserLoginSerializer
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from rest_framework.views import APIView  # for logout
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import NotFound
from rest_framework.renderers import TemplateHTMLRenderer
from django.shortcuts import render, redirect
from .forms import LoginForm, UpdateProfileForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

# Use this class for Registration
class UserRegistrationView(generics.CreateAPIView):
    serializer_class = UserRegistrationSerializer

    def get(self, request, *args, **kwargs):
        # Handle GET request logic here (e.g., render a registration form)
        return Response({"message": "Registration form"}, status=status.HTTP_200_OK)

    # Use the method to send the information of user
    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


# Use this class for login
class UserLoginView(ObtainAuthToken):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'login_test.html'

    error_messages = {
        'invalid': "Invalid username or password",
        'disabled': "Sorry, this account is suspended",
    }

    def _error_response(self, message_key):
        return Response({
            'success': False,
            'message': self.error_messages[message_key],
            'user_id': None,
        }, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request):
        #form = LoginForm() # this way is for render()
        #return render(request, 'login_test.html', {'form': form})
        profile = Profile.objects.all()
        serializer = UserLoginSerializer()
        return Response({'serializer': serializer, 'profile': profile})

    def post(self, request, *args, **kwargs):
        user = None
        username = request.data.get('username')
        password = request.data.get('password')
        email = request.data.get('email')
        # print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        # print("Received POST request for user login")
        # print("Username:", username)
        # print("Email:", email)
        if email :
            try:
                user = authenticate(email=email, password=password)
            except ObjectDoesNotExist:
                pass
        
        if not user:
            user = authenticate(username=username, password=password)
            
        if user:
            login(request, user)  # Log in the user
            token, _ = Token.objects.get_or_create(user=user)
            request.session['auth_token'] = token.key
            #print(token)  
            return redirect('user:profile')
            # return Response({
            #     'success': True,
            #     'message': "Login successful",
            #     'token': token.key,
            #     'user_id': user.id,
            # }, status=status.HTTP_200_OK)
        else:
            return self._error_response('disabled')
        

#TODO:add html
# Use this class for logout 
class UserLogoutView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        try:
            # delete the user's token
            token = Token.objects.get(user=request.user)
            #print(Token.objects.get(user=request.user))
            token.delete()
            return Response({'message': 'Successfully logged out.'}, status=status.HTTP_200_OK)
        except Token.DoesNotExist:
            # Token does not exist, user is effectively logged out already
            raise NotFound(detail='Token not found - User is not aunthenticate', code=status.HTTP_401_UNAUTHORIZED)
        except Exception as e:
            # Handle other exceptions (e.g., database errors) appropriately
            return Response({'error': 'An error occurred during logout.'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        

# Class is specified in the request get for profile page
class ProfileView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'profile.html'

    permission_classes = (IsAuthenticated,)
    def get(self, request):
        try:
            user = request.user  # Get the authenticated user
            #print(user.profile.avatar)
            profile_data = {
                'username': user.username,
                'email': user.email,
                'bio': user.profile.bio,
                'avatar': user.profile.avatar
            }
            print(Token.objects.get(user=request.user))
            return Response(profile_data)
        except Token.DoesNotExist:
            # Token does not exist, user is effectively logged out already
            raise NotFound(detail='Token not found - User is not aunthenticate', code=status.HTTP_401_UNAUTHORIZED)
        except Exception as e:
            # Handle other exceptions (e.g., database errors) appropriately
            return Response({'error': 'An error occurred during logout.'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


# Class is specified in the request get/post for update profile page
class ProfileUpdateView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        try:
            profile_form = UpdateProfileForm(instance=request.user.profile)
            return render(request, 'update_profile.html', {'form': profile_form})
        except Token.DoesNotExist:
            # Token does not exist, user is effectively logged out already
            raise NotFound(detail='Token not found - User is not aunthenticate', code=status.HTTP_401_UNAUTHORIZED)
        except Exception as e:
            # Handle other exceptions (e.g., database errors) appropriately
            print(e)
            return Response({'error': 'An error occurred during profile update.'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        
    def post(self, request):
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='user:profile')
        

class AddFriendView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'add_friend.html'
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        # Handle GET request logic here (e.g., render a registration form)
        return Response({"message": "Add Friend"}, status=status.HTTP_200_OK)
    def post(self, request):
        user_email = request.POST.get('user_email')
        try:
            user = User.objects.get(email=user_email)
        except User.DoesNotExist:
            return Response({"error": "User not found"}, status=status.HTTP_404_NOT_FOUND)
        
        friend_profile = get_object_or_404(Profile, user=user)
        user_profile = get_object_or_404(Profile, user=request.user)
        # Check if the friendship already exists
        if Friend.objects.filter(profile_one=user_profile, profile_two=friend_profile).exists() or \
           Friend.objects.filter(profile_one=friend_profile, profile_two=user_profile).exists():
            return Response({"error": "Friendship already exists"}, status=status.HTTP_400_BAD_REQUEST)
        # Create a new friendship
        friend1 = Friend(profile_one=user_profile, profile_two=friend_profile)
        friend2 = Friend(profile_one=friend_profile, profile_two=user_profile)
        friend1.save()
        friend2.save()

        return Response({"message": "Friend added successfully"}, status=status.HTTP_201_CREATED)

our_chat/user/templates/add_friend.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-3">
    <h2>Add Friend</h2>
    <form method="post">
        {% csrf_token %}
        
        <label for="user_email">Email:</label>
        <input type="text" id="user_email" name="user_email"><br><br>
        <button type="submit">Add Friend</button>
    </form>

{% endblock %}

our_chat/user/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Chat{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css'%}">
    <!-- Add more static files if needed -->
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                
                
                <form method="post" action="{% url 'user:user-logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                </form>
                <a class="nav-link" href="{% url 'user:user-login' %}">Login</a>
                <a class="nav-link" href="{% url 'user:user-registration' %}">Signup</a>
                <a class="nav-link" href="{% url 'user:profile' %}">Profile</a>
                <a class="nav-link" href="{% url 'user:update-profile' %}">Update Profile</a>
                <a class="nav-link" href="{% url 'user:add-friend' %}">Add Friend</a>
            </div>
        </div>
    </div>
</nav>

<div class="container mt-3">
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

our_chat/user/templates/login.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log-in"></p>
    </form>
{% endblock %}

our_chat/user/templates/login_test.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Login User</h2>

<form method="POST">
    {% csrf_token %}
    <label for="email">Email:</label>
    <input type="text" id="email" name="email"><br><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password"><br><br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

{% endblock %}

our_chat/user/templates/profile.html
{% extends 'base.html' %}
{% block content %}
    <h1>Profile Information</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">User Profile</h5>
            <img src="{{ avatar.url }}" alt="Image">
            <p class="card-text">Name: {{ username }}</p>
            <p class="card-text">Email: {{ email }}</p>
            <p class="card-text">Bio: {{bio}}</p>
            <!-- Add more profile information here -->
        </div>
    </div>
{% endblock %}

our_chat/user/templates/update_profile.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>
{% endblock %}