our_chat/chat/urls.py
from django.urls import path
from .views import MyChatsView

app_name = "chat"

urlpatterns = [
    path('my-chats/', MyChatsView.as_view(), name='my_chats'),
    path('chat-with/<str:id>', MyChatsView.as_view(), name='chat-with'),
]

our_chat/our_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('chat/', include('chat.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

our_chat/chat/models.py
from django.db import models

# Create your models here.

our_chat/chat/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework import status
from user.models import Friend
from django.db.models import Q

# Class with all defined friends(contacts)
class MyChatsView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name ='my_chats.html'

    permission_classes = (IsAuthenticated,)
    
    def get(self, request):
        try:
            user = request.user  
            #friends = Friend.objects.filter(Q(profile_one=user.profile) | Q(profile_two=user.profile))
            friends = Friend.objects.filter(Q(profile_one=user.profile))
            friend_data = []
            for friend in friends:
                friend_data.append(friend)
            return Response({'friends': friend_data})
        except Exception as e:
            return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

our_chat/chat/templates/my_chats.html
{% extends 'base.html' %}

{% block title %}All Quotes{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'chat/all_chats.css' %}">

<div class="container mt-3">
    <h2>All Friends</h2>

    {% for friend in friends %}
    <div class="friend-box">
        <img src="{{ friend.profile_two.avatar.url }}" alt="Image">
        <a href="{% url 'chat:chat-with' friend.profile_two.user.id %}">
            {{ friend.profile_two.user.username }}
        </a>
        
    </div>    
    {% endfor %}
        
    
</div>
{% endblock %}